:lib: pass:quotes[_library_]
:libs: pass:quotes[_libraries_]
:j: Java
:fs: functies
:f: functie
:m: method
:icons: font
:source-highlighter: rouge
:am: Access Modifier

//ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
//endif::[]

= Access Modifiers
//Author Mark Nuyts
//v0.1
:toc: left
:toclevels: 4

_Access Modifiers_ bepalen de _zichtbaarheid_ van variabelen en methods ten opzichte van andere klassen. _Public_ en _private_ zijn 2 voorbeelden van de _Access Modifiers_.

== Waarom gebruik maken van de Access Modifiers?

Het gebruik van {am}s laat ons toe te bepalen welke variabelen of methods zichtbaar zijn voor andere klassen:

* Indien variabelen of methods #niet relevant zijn voor andere klassen#, kunnen we ze verbergen.
* Ook laat het toe details van de implementatie (die achteraf nog kunnen veranderen) 'geheim' te houden. #Op deze manier kan de implementatie van de klasse achteraf nog aangepast worden#, zonder dat dit impact heeft op de klassen die gebruik maken van deze klasse.

== De verschillende Access Modifiers

* Public
* Private
* Package private
* Protected

=== Public

#De variabele of method is zichtbaar voor iedere andere klasse in het programma (in eender welk package)#:

[source,java]
----
public class Car {
  public int pk = 400;
  public void drive(){
    System.out.println("driving the car at "+ pk +"HP"); 
  }
}

public class Starter {
  public static void main(String[] args){
    Car c = new Car();
    c.pk; <1>
    c.drive(); <2>
  }
}
----
<1> We kunnen aan de publieke variabele
<2> We kunnen aan de publieke method


=== Private

#De variabele of method is zichtbaar voor iedere andere klasse in het programma#:

[source,java]
----
public class Car {
  private int pk = 400;
  private void drive(){
    System.out.println("driving the car at "+ pk +"HP"); 
  }
}

public class Starter {
  public static void main(String[] args){
    Car c = new Car();
    c.; <1>
    c.; <2>
  }
}
----
<1> We kunnen niet aan de private variabele
<2> We kunnen niet aan de private method

=== Package Private (de default)

Deze {am} is actief indien we geen expliciete {am} toevoegen.
#De variabelen of methods zijn toegankelijk vanuit klassen die in hetzelfde _package_ zitten#.

[source,java]
----
package CARS;
public class Car {
  int pk = 400; <1>
  void drive(){
    System.out.println("driving the car at "+ pk +"HP"); 
  }
}

package CARS;
public class Engine {
  public static void main(String[] args){
    Car c = new Car();
    c.pk; <2>
  }
}

package USERS;
public class Starter {
  public static void main(String[] args){
    Car c = new Car();
    c.; <3>
  }
}
----
<1> De Access Modifier leeg laten -> Package private
<2> Zichtbaar: in hetzelfde package.
<3> Onzichtbaar: in een ander package.

=== Protected

#De variabelen of methods zijn toegankelijk vanuit klassen die in hetzelfde _package_ zitten *of* klassen die een *subklasse* van de klasse zijn#.

[source,java]
----
package CARS;
public class Car {
  protected int pk = 400;
  protected void drive(){
    System.out.println("driving the car at "+ pk +"HP"); 
  }
}

package CARS;
public class Engine {
  public static void main(String[] args){
    Car c = new Car();
    c.pk; <1>
  }
}

package USERS;
public class Starter {
  public static void main(String[] args){
    Car c = new Car();
    c.; <2>
  }
}

package USERS;
public class RaceCar extends Car {
  public void calculate(){
    super.pk; <3>
  }
}
----
<1> Variabele zichtbaar, want de klasse zit in dezelfde package als de protected klasse.
<2> Onzichtbaar, want in een ander package en geen subklasse.
<3> Zichtbaar: ander package, maar wel een subklasse.
