:lib: pass:quotes[_library_]
:libs: pass:quotes[_libraries_]
:j: Java
:fs: functies
:f: functie
:m: method
:icons: font
:source-highlighter: rouge
:am: Access Modifier

//ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
//endif::[]

= Equals en Hashcode
//Author Mark Nuyts
//v0.1
:toc: left
:toclevels: 4

Instanties moeten regelmatig gecontroleerd worden op 'het identiek zijn' van elkaar. Bijvoorbeeld bij het toevoegen van instanties in een Set, mag er telkens maar 1 unieke instantie in de set zitten, dubbele waarden moeten vermeden worden.
De controle op deze uniekheid gebeurt door 2 instanties met elkaar te vergelijken en na te gaan of ze identiek zijn met elkaar.

Dit kan op 2 manieren gebeuren:

. Via *hashcode*.
. Via *equals*.

Het verschil tussen de twee, is dat _equals_ gebruikt wordt om 2 objecten te vegelijken, terwijl _hashCode_ gebruikt wordt om te beslissen of 2 objecten in dezelfde groep gecategoriseerd kunnen worden (als identiek beschouwd worden in bijvoorbeeld een lijst of map).

== Equals en hashcode in een java klasse

Iedere java klasse is een _subclass_ van Object. In Object bestaat er de equals en de hashcode methods:

[source, java]
----
public boolean equals(Object obj) { <1>
      return (this == obj);
}
    
@HotSpotIntrinsicCandidate <2>
public native int hashCode();
----
<1> Standaard vergelijkt de equals of het andere object hetzelfde geheugenadres heeft als het huidige object.
<2> Standaard wordt de ingebouwde implementatie genomen die in de java virtuele machine aanwezig is (kijken naar het geheugenadres).

Voor klassen en instanties die echt data gaan bijhouden, volstaat deze standaard implementatie echter niet.
Java klassen die met elkaar vergeleken moeten kunnen worden, zijn klassen die data gaan bijhouden. Bijvoorbeeld een Person (naam, geboortedatum,...), complexe getallen (reëel en imaginair gedeelte), matrixen, ...
Hiervoor kunnen we de equals en hashcode methods gaan *overriden*.

Hiervoor de gebruiken we het volgende voorbeeld:

[source,java]
----
class Money {
    int amount;
    String currencyCode;
}
Money income = new Money(55, "USD");
Money expenses = new Money(55, "USD");
boolean balanced = income.equals(expenses)
----

Indien we de equals en hashcode niet aanpassen, is de income niet gelijk aan de balance (want een ander geheugenadres).
Het is dus nodig om de waarden van de variabelen te gaan vergelijken.

== Equals

[source,java]
----
@Override
public boolean equals(Object o) {
    if (o == this)
        return true;
    if (!(o instanceof Money))
        return false;
    Money other = (Money)o;
    boolean currencyCodeEquals = (this.currencyCode == null && other.currencyCode == null)
      || (this.currencyCode != null && this.currencyCode.equals(other.currencyCode));
    return this.amount == other.amount && currencyCodeEquals;
}
----

Java specifieerd de voorwaarden waaraan een equals() moet voldoen. De equals implementatie moet:

* *reflexief* zijn: een object moet gelijk zijn aan zichzelf.
* *symmetrisch* zijn: x.equals(y) moet hetzelfde resultaat geven dan y.equals(x).
* *transitief* zijn: als x.equals(y) en y.equals(z), dan moet ook x.equals(z)
* *consistent* zijn: de waarde van de equals mag enkel veranderen indien een variabele waarmee de equals rekening houdt, ook veranderd (het mag dus niet van het toeval afhangen).

=== Overerving en equals

Het aanmaken van een subklasse, kan ervoor zorgen dat het equals contract niet wordt nagekomen:

[source,java]
----
class WrongVoucher extends Money {

    private String store;

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof WrongVoucher))
            return false;
        WrongVoucher other = (WrongVoucher)o;
        boolean currencyCodeEquals = (this.currencyCode == null && other.currencyCode == null)
          || (this.currencyCode != null && this.currencyCode.equals(other.currencyCode));
        boolean storeEquals = (this.store == null && other.store == null)
          || (this.store != null && this.store.equals(other.store));
        return this.amount == other.amount && currencyCodeEquals && storeEquals;
    }

    // other methods
}
----

Op het eerste zicht lijkt de override voor de _equals()_ in de Voucher klasse correct.
Dit is echter enkel het geval als we Money met Money vergelijken en Voucher met Voucher.
Indien we Money met Voucher zouden vergelijken loopt het hier mis:

[source,java]
----
Money cash = new Money(42, "USD");
WrongVoucher voucher = new WrongVoucher(42, "USD", "Amazon");

voucher.equals(cash) => false // Zoals verwacht.
cash.equals(voucher) => true // Dit is een foutief resultaat.
----

Dus aan de symmetrie vereiste is hier niet voldaan!

=== compositie in plaats van overerving

Om deze fout te vermijden, kunnen we beter gebruik maken van _compositie_ in plaats van overerving.

In plaats van een subklasse van Money te maken, zouden we een Voucher klasse met een Money variabele kunnen aanmaken:

[source,java]
----
class Voucher {

    private Money value;
    private String store;

    Voucher(int amount, String currencyCode, String store) {
        this.value = new Money(amount, currencyCode);
        this.store = store;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Voucher))
            return false;
        Voucher other = (Voucher) o;
        boolean valueEquals = (this.value == null && other.value == null)
          || (this.value != null && this.value.equals(other.value));
        boolean storeEquals = (this.store == null && other.store == null)
          || (this.store != null && this.store.equals(other.store));
        return valueEquals && storeEquals;
    }

    // other methods
}
----


== Hashcode

De _hashCode_ functie geeft een integer terug die uniek is voor de instantie.
De waarde kunnen we berekenen op basis van de variabelen van de klasse en zou moeten overeenkomen met de uniekheid van de equals method. 
indien de _equals()_ geoverride wordt, overriden we best ook de _hashCode_.

=== Het hashcode contract

Het contract van de _hashCode_ is gerelateerd aan deze van de _equals_ en moet aan de volgende zaken voldoen:

internal consistency: De waarde van de hashcode mag enkel veranderen indien een variabele veranderdt die ook in de equals opgenomen is.
equals consistency: Objecten die volgens de equals gelijk zijn, moeten dezelfde hashcode teruggeven.
collisions: objecten die volgens de equals niet gelijk zijn, mogen wel dezelfde hashcode hebben.

=== Hashcode en equals consistentie

De tweede vereiste van de _hashCode_ geeft aan dat: **de hashCode steeds override moet worden indien de equals aangepast werd**.


Bijvoorbeeld:

[source,java]
----
class Team {

    String city;
    String department;

    @Override
    public final boolean equals(Object o) {
        // implementation
    }
}
----

The Team class overrides only equals(), but it still implicitly uses the default implementation of hashCode() as defined in the Object class. 
And this returns a different hashCode() for every instance of the class. 
This violates the second rule.

Now, if we create two Team objects, both with city “New York” and department “marketing,” they will be equal, but they'll return different hashCodes.

3.3. HashMap Key With an Inconsistent hashCode()
But why is the contract violation in our Team class a problem? Well, the trouble starts when some hash-based collections are involved. Let's try to use our Team class as a key of a HashMap:

[source,java]
----
Map<Team,String> leaders = new HashMap<>();
leaders.put(new Team("New York", "development"), "Anne");
leaders.put(new Team("Boston", "development"), "Brian");
leaders.put(new Team("Boston", "marketing"), "Charlie");

Team myTeam = new Team("New York", "development");
String myTeamLeader = leaders.get(myTeam);
----

We would expect myTeamLeader to return “Anne,” but with the current code, it doesn't.



If we want to use instances of the Team class as HashMap keys, we have to override the hashCode() method so that it adheres to the contract; equal objects return the same hashCode.

Let's see an example implementation:

[source,java]
----
@Override
public final int hashCode() {
    int result = 17;
    if (city != null) {
        result = 31 * result + city.hashCode();
    }
    if (department != null) {
        result = 31 * result + department.hashCode();
    }
    return result;
}
----

After this change, leaders.get(myTeam) returns “Anne” as expected.

== Wanneer overriden we best equals en hashcode

Generally, we want to override either both of them or neither of them. We just saw in Section 3 the undesired consequences if we ignore this rule.

Domain-Driven Design can help us decide circumstances when we should leave them be. For entity classes, for objects having an intrinsic identity, the default implementation often makes sense.

However, for value objects, we usually prefer equality based on their properties. Thus, we want to override equals() and hashCode(). Remember our Money class from Section 2: 55 USD equals 55 USD, even if they're two separate instances.
