:lib: pass:quotes[_library_]
:libs: pass:quotes[_libraries_]
:j: Java
:fs: functies
:f: functie
:m: method
:icons: font
:source-highlighter: rouge

= Functies en Methods
//Author Mark Nuyts
//v0.1
:toc: left
:toclevels: 4

Functies (of methods) zijn stukken code die een naam hebben gekregen.
Ze worden buiten de _main_ {m} geschreven.  
De code van een functie wordt alleen maar uitgevoerd wanneer de functie wordt opgeroepen. 
Als een programma (of de _main_ method) veel dezelfde code bevat (herhaling),
kan je de code die altijd hetzelfde is apart zetten in een functie en die functie telkens opnieuw oproepen.

== Het definiëren van een {f}.

Een functie wordt gedefiniëerd met behulp van enkele keywords:

. *public* : bepaald of de functie overal bruikbaar is (dit kan gelimiteerd worden)
. *static* : er is geen instantie van de klasse nodig om deze functie te gebruiken
. *void* : het return type. Void (= leegte in het Engels), geeft aan dat er geen return type wordt gebruikt.
. *de functienaam*.

.Een voorbeeld van een functie.
[source,java]
----
public static <3> void <1> voorbeeldFunctie <2> () { <5>
		System.out.println("Hello World!"); <4>
} <5>
----
<1> Het datatype dat de functie teruggeeft. In dit geval _void_ (een leegte), dus niets.
<2> De naam van de functie.
<3> Static: geeft aan dat er geen instantie nodig is van de klasse om de functie uit te voeren.
<4> De code die in de functie wordt uitgevoerd (indien de functie aangeroepen wordt).
<5> De code binnen een functie, moet tussen accolades staan.

Bovenstaande functie geeft een stuk _code_ aan die een naam (of een noemer) heeft gekregen, namelijk _voorbeeldFunctie_.
Dit stuk _code_ kan meermaals aangeroepen worden.

[IMPORTANT]
====
Een speciale functie, of method, is de _main method_. 
Deze bepaalt het startpunt van een {j} programma.
De definitie van deze functie heeft een vaste structuur.


.De main method.
[source,java]
----
include::Functies.java[lines=3]
----
====


== Functies oproepen

Om een functie (en dus een stuk _code_) op te roepen, maak je gebruik van de naam van functie, gevolgd door ronde haken:
.De voorbeeldfunctie aanroepen.
[source,java]
----
include::Functies.java[lines=3;4;17]
----

Iedere keer de main functie (of main method) aangeroepen wordt (dus iedere keer je het programma start), wordt ook bovenstaande functie op zijn beurt aangeroepen.
De _code_ in de functie wordt op dat moment uitgevoerd.

Als output krijg je dat er _"Hello world!"_ naar de console wordt geprint.

== Functies met parameters

Aan een functie kan je variabelen meegeven.
Deze variabelen worden meegegeven bij het oproepen van de functie. Bijvoorbeeld:
[source,java]
----
include::Functies.java[lines=3;5;17]
----
Dit zorgt ervoor dat in de volgende functie:

[source,java]
----
include::Functies.java[lines=23..25]
----
De tekst "Erik" wordt meegegeven als _naam_. 
Deze naam _**parameter**_ (of tijdelijke variabele) kan gebruikt worden in de _code_ van de functie.


=== Argumenten

Iedere keer dat de functie wordt opgeroepen kan de naam *parameter* anders ingevuld worden:
[source,java]
----
include::Functies.java[lines=3;6;7;8;17]
----

Iedere keer dat deze functie wordt aangeroepen, wordt er een andere naam naar de console geschreven.
Dit terwijl in de _code_ van de functie onveranderd blijft.
Er worden verschillende *argumenten* meegegeven aan de *parameter* van de functie.

== Functies oproepen in functies

Tot nu toe hebben we functies altijd opgeroepen vanuit de main functie (of method).
Dit hoeft echter niet.
Je kan perfect iedere functie oproepen vanuit een andere functie.
Bijvoorbeeld:
[source,java]
----
include::Functies.java[lines=39..43]
----


== Meerdere parameters

[source,java]
----
include::Functies.java[lines=27..29]
----


== Return types

[source,java]
----
include::Functies.java[lines=62..65]
----

=== Gebruik maken van functies met return types

Als je een functie oproept die een return type heeft, kan je het resultaat van de functie opslaan in een variabele. 
Deze variabele kan je achteraf verder gebruiken in je _code_.
Het resultaat van het oproepen van een functie met een return type is een tijdelijke variabele van het type van het return type.

[source,java]
----
include::Functies.java[lines=3;14;17]
----

== Functies combineren
Vanuit functies kan je andere functies oproepen.
Dit maakt het mogelijk in een bepaalde functie gebruik te maken van andere functies die onderliggende (complexe) zaken voor hun rekening nemen.
Hierdoor kan je functies schrijven die zich focussen op hun eigen taak.
Zie het voorbeeld hieronder:

[source,java]
----
include::Functies.java[lines=55..65]
----


