:lib: pass:quotes[_library_]
:libs: pass:quotes[_libraries_]
:j: Java
:fs: functies
:f: functie
:m: method
:icons: font
:source-highlighter: rouge

//ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
//endif::[]

= Functies en Methods
//Author Mark Nuyts
//v0.1
:toc: left
:toclevels: 4

Functies (of methods) zijn stukken code die een naam hebben gekregen.
Ze worden buiten de _main_ {m} geschreven.  
De code van een functie wordt alleen maar uitgevoerd wanneer de functie wordt opgeroepen. 
Als een programma (of de _main_ method) veel dezelfde code bevat (herhaling),
kan je de code die altijd hetzelfde is apart zetten in een functie en die functie telkens opnieuw oproepen.

== Het definiëren van een {f}.

Een functie wordt gedefiniëerd met behulp van enkele keywords:

. *public* : bepaalt of de functie overal bruikbaar is (dit kan gelimiteerd worden, hier komen we later in de cursus op terug).
. *static* : er is geen instantie van de klasse nodig om deze functie te gebruiken.
. *void* : het return type. Void (= leegte in het Engels), geeft aan dat er geen return type wordt gebruikt.
. *de functienaam*.

.Een voorbeeld van een functie.
[source,java]
----
public <6>
	static <3>
		void <1>
			voorbeeldFunctie() <2>
{  <5>
		System.out.println("Hello World!"); <4>
} <5>
----
<1> Het datatype dat de functie teruggeeft. In dit geval _void_ (een leegte), dus niets.
<2> De naam van de functie.
<3> Static: geeft aan dat er geen instantie nodig is van de klasse om de functie uit te voeren.
<4> De code die in de functie wordt uitgevoerd (indien de functie aangeroepen wordt).
<5> De code binnen een functie, moet tussen accolades staan.
<6> De _access modifier_ , dit komt later in de cursus aan bod, public wilt zeggen dat de functie oproepbaar is vanuit alle klassen.

Bovenstaande functie geeft een stuk _code_ aan die een naam (of een noemer) heeft gekregen, namelijk _voorbeeldFunctie_.
Dit stuk _code_ kan meermaals aangeroepen worden.

[IMPORTANT]
====
Een speciale functie, of method, is de _main method_. 
Deze bepaalt het startpunt van een {j} programma.
De definitie van deze functie heeft een vaste structuur.


.De main method.
[source,java]
----
include::Functies.java[lines=3]
----
====


== Functies oproepen

Om een functie (en dus een stuk _code_) op te roepen, maak je gebruik van de naam van functie, gevolgd door ronde haken:
.De voorbeeldfunctie aanroepen.
[source,java]
----
include::Functies.java[lines=3;4;17]
----

Iedere keer de main functie (of main method) aangeroepen wordt (dus iedere keer je het programma start), wordt ook bovenstaande functie op zijn beurt aangeroepen.
De _code_ in de functie wordt op dat moment uitgevoerd.

Als output krijg je dat er _"Hello world!"_ naar de console wordt geprint.

== Functies met parameters

Aan een functie kan je variabelen meegeven.
Deze variabelen worden meegegeven bij het oproepen van de functie. Bijvoorbeeld:
[source,java]
----
include::Functies.java[lines=3;5;17]
----
Dit zorgt ervoor dat in de volgende functie:

[source,java]
----
include::Functies.java[lines=23..25]
----
De tekst "Erik" wordt meegegeven als _naam_. 
Deze naam _**parameter**_ (of tijdelijke variabele) kan gebruikt worden in de _code_ van de functie.


=== Argumenten

Iedere keer dat de functie wordt opgeroepen kan de naam *parameter* anders ingevuld worden:
[source,java]
----
include::Functies.java[lines=3;6;7;8;17]
----

Iedere keer dat deze functie wordt aangeroepen, wordt er een andere naam naar de console geschreven.
Dit terwijl in de _code_ van de functie onveranderd blijft.
Er worden verschillende *argumenten* meegegeven aan de *parameter* van de functie.

== Functies oproepen in functies

Tot nu toe hebben we functies altijd opgeroepen vanuit de main functie (of method).
Dit hoeft echter niet.
Je kan perfect iedere functie oproepen vanuit een andere functie.
Bijvoorbeeld:
[source,java]
----
include::Functies.java[lines=39..43]
----


== Meerdere parameters

Je kan een functie meerdere parameters geven. 
Iedere keer dat de functie wordt opgroepen, moeten deze parameters ingevuld worden. 
Je gaat dus iedere keer argumenten moeten meegeven.

[source,java]
----
include::Functies.java[lines=27..29]
----

Bovenstaande functie kunnen we oproepen op de volgende manier:

[source,java]
----
zegHalloMetLeeftijd("Nathan", 17){
----

== Return types

Een return type geeft aan welk resultaat een functie teruggeeft als hij opgeroepen wordt.
Tot nu toe werkten we met het _void_ datatype. Dit geeft een leegte aan (dus niets werd er teruggegeven).
We kunnen echter kiezen uit verschillende datatypes om terug te geven:

* int : voor gehele getallen.
* String : voor tekst.
* double : voor kommagetallen.
* Klassen : voor instanties van klassen (zien we later in de cursus)
* boolean : true/false (waar / niet waar).
* Arrays
* ..

[source,java]
----
include::Functies.java[lines=62..65]
----

In het bovenstaande voorbeeld werd het *return type* datatype aangepast van _void_ naar _double_.
Dit verplicht de code in de functie een resultaat terug te geven of te _returnen_.
Dit wordt aangegeven met het *return* _keyword_.

[source,java]
----
public static 
		double <1>
			berekenoppervlaktevancirkel(int straal) {
				double oppervlakte = 3.1415 * straal * straal;<2>
				return oppervlakte;<3>
			}
----
<1> Het _return type_ : dit geeft aan welk datatype de functie zal teruggeven.
<2> Een berekening van een variabele.
<3> Het teruggeven of _returnen_ van een variabele.

[IMPORTANT]
====
De variabele die wordt teruggegeven *moet* verplicht van hetzelfde datatype zijn als het _return type_ van de functie.
====

=== Gebruik maken van functies met return types

Als je een functie oproept die een return type heeft, kan je het resultaat van de functie opslaan in een variabele. 
Deze variabele kan je achteraf verder gebruiken in je _code_.
Het resultaat van het oproepen van een functie met een return type is een tijdelijke variabele van het type van het return type.

[source,java]
----
include::Functies.java[lines=3;14;17]
----

== Functies combineren
Vanuit functies kan je andere functies oproepen.
Dit maakt het mogelijk in een bepaalde functie gebruik te maken van andere functies die onderliggende (complexe) zaken voor hun rekening nemen.
Hierdoor kan je functies schrijven die zich focussen op hun eigen taak.
Zie het voorbeeld hieronder:

[source,java]
----
include::Functies.java[lines=55..65]
----


