:lib: pass:quotes[_library_]
:libs: pass:quotes[_libraries_]
:j: Java
:fs: functies
:f: functie
:m: method
:source-highlighter: rouge
:icons: font

//ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
//endif::[]

= If / Else
//Author Mark Nuyts
//v0.1
:toc: left
:toclevels: 4

Met een if/else statement kunnen we het uitvoeren van code laten afhangen van een bepaalde _waar/niet-waar_ (_true/false_) stelling.

== Boolean conditie

Een boolean conditie is een _waar/niet-waar_ stelling:

[source,java]
----
int getal = 5;
boolean conditie = getal < 6; <1>
----
Deze boolean wordt geëvalueerd naar _True_ want het getal 5 is kleiner dan 6.

== If / else

Een voorbeeld van een if/else statement:
[source,java]
----
int getal = 5;
if (getal < 10){ <1>
  System.out.println("het getal is kleiner dan 10"); <2>
} else { <3>
  System.out.println("Het getal is niet kleiner dan 10"); <4>
} <5>
----
<1> De boolean conditie die gaat bepalen of we in het if statement terecht komen, ofwel of we in het else gedeelte terecht komen.
<2> Deze code wordt uitgevoerd indien de boolean conditie _true_ is.
<3> De else (anders) geeft aan wat er moet gebeuren indien de boolean conditie _false_ is.
<4> Deze code wordt uitgevoerd indien indien de boolean conditie _false_ is.
<5> Sluit de if statements steeds af met een curly brace.

In dit geval wordt afgeprint:
----
het getal is kleiner dan 10
----

== Else if

Naast _if/else_, bestaat ook de stuctuur _if / else if / else_.
Deze _else if_ kan meermaals herhaald worden:

[source,java]
----
int getal = 526;

if (getal > 1000){
// getal is groter dan 1000;
} else if (getal < 600) {
// getal is kleiner dan 600
} else if (getal < 700) {
// getal is kleiner dan 600
} else {
// alle andere gevallen
}
----

== Vergelijken van condities

* Kleiner dan: a < b
* Kleiner dan of gelijk aan: a <= b
* Groter dan: a > b
* Groter dan of gelijk aan: a >= b
* Gelijk aan: a == b
* Niet gelijk aan: a != b

